// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentskaSluzba.Data;

namespace StudentskaSluzba.Migrations
{
    [DbContext(typeof(StudentskaSluzbaContext))]
    [Migration("20210212210511_PrvaMigracija")]
    partial class PrvaMigracija
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StudentskaSluzba.Models.Predmet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("ECTS")
                        .HasColumnType("double");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Predmet");
                });

            modelBuilder.Entity("StudentskaSluzba.Models.Student", b =>
                {
                    b.Property<string>("Ime")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("BrojIndeksa")
                        .HasColumnType("int");

                    b.Property<int>("GodinaStudija")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Ime");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("StudentskaSluzba.Models.UpisNaPredmet", b =>
                {
                    b.Property<string>("BrojProtokola")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("AkademskaGodina")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DatumUpisa")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("BrojProtokola");

                    b.ToTable("UpisNaPredmet");
                });
#pragma warning restore 612, 618
        }
    }
}
